version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
        auth:
          username: longdinh
          password: $DOCKERHUB_PASSWORD
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: |
          if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
            curl https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar -o $CIRCLE_WORKING_DIRECTORY/gradle/wrapper/gradle-wrapper.jar
          fi
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run App
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results